[2021-10-21 12:12:00,380] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: bigquery.upload scheduled__2021-10-20T10:11:19.681737+00:00 [queued]>
[2021-10-21 12:12:00,384] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: bigquery.upload scheduled__2021-10-20T10:11:19.681737+00:00 [queued]>
[2021-10-21 12:12:00,384] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-21 12:12:00,384] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-21 12:12:00,384] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-21 12:12:00,388] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): upload> on 2021-10-20 10:11:19.681737+00:00
[2021-10-21 12:12:00,393] {standard_task_runner.py:52} INFO - Started process 23090 to run task
[2021-10-21 12:12:00,397] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'bigquery', 'upload', 'scheduled__2021-10-20T10:11:19.681737+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/csv_2_bigquery.py', '--cfg-path', '/var/folders/fc/65rvsktx5tv__l89pnq2m4pw0000gn/T/tmpjhbloir5', '--error-file', '/var/folders/fc/65rvsktx5tv__l89pnq2m4pw0000gn/T/tmpsiqlh7uf']
[2021-10-21 12:12:00,398] {standard_task_runner.py:77} INFO - Job 8: Subtask upload
[2021-10-21 12:12:00,418] {logging_mixin.py:109} INFO - Running <TaskInstance: bigquery.upload scheduled__2021-10-20T10:11:19.681737+00:00 [running]> on host 28.0.168.192.in-addr.arpa
[2021-10-21 12:12:00,433] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=vinzenz@9fwr.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=bigquery
AIRFLOW_CTX_TASK_ID=upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-20T10:11:19.681737+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-20T10:11:19.681737+00:00
[2021-10-21 12:12:00,433] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/fc/65rvsktx5tv__l89pnq2m4pw0000gn/T
[2021-10-21 12:12:00,434] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /Users/cesareborgia/Desktop/9fwr/airflow_use_case/get_data.py; echo success']
[2021-10-21 12:12:00,447] {subprocess.py:85} INFO - Output:
[2021-10-21 12:12:00,553] {subprocess.py:89} INFO - Traceback (most recent call last):
[2021-10-21 12:12:00,554] {subprocess.py:89} INFO -   File "/Users/cesareborgia/Desktop/9fwr/airflow_use_case/get_data.py", line 2, in <module>
[2021-10-21 12:12:00,554] {subprocess.py:89} INFO -     import pandas as pd
[2021-10-21 12:12:00,554] {subprocess.py:89} INFO - ModuleNotFoundError: No module named 'pandas'
[2021-10-21 12:12:00,561] {subprocess.py:89} INFO - success
[2021-10-21 12:12:00,562] {subprocess.py:93} INFO - Command exited with return code 0
[2021-10-21 12:12:00,570] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=bigquery, task_id=upload, execution_date=20211020T101119, start_date=20211021T101200, end_date=20211021T101200
[2021-10-21 12:12:00,593] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-21 12:12:00,602] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
